version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: install dependensi
        command: |
          npm install --save
        # run tests!
      - run: yarn test
        # run dev!
        # - run: yarn dev
workflows:
  build_test:
    jobs:
      -run_tests