version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
      - image: circleci/mariadb:10.2
        environment:
          - MYSQL_DATABASE: empatkali
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password
    working_directory: ~/my_repo
    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import
          command: |
            yarn sequelize db:migrate
      - run:
          name: install dependecies
          command: |
            yarn install --save
      - run:
          name: run test
          command: |
            yarn test
workflows:
  build_test:
    jobs:
    - run_tests