version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependecies
          command: |
            yarn install --save
      - run:
          name: run test
          command: |
            yarn test
workflows:
  build_test:
    jobs:
    - run_tests