version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
      - image: circleci/mariadb:bionic
        environment:
          - MYSQL_ROOT_PASSWORD: password
          - MYSQL_DATABASE: empatkali
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            mysql -h 127.0.0.1 -u admin -password empatkali < sql-data/dummy.sql
      - run:
          name: install dependecies
          command: |
            yarn install --save
      - run:
          name: run test
          command: |
            yarn test
workflows:
  build_test:
    jobs:
    - run_tests